number_of_random_ips: 15
connect_timeout: 1
ip_ranges_file: "./ipv6.txt" #https://www.cloudflare.com/ips-v6
test_url:
  protocol: "https:"
  host: "apple.freecdn.workers.dev"
  path: "/105/media/us/iphone-11-pro/2019/3bd902e4-0752-4ac1-95f8-6225c32aec6d/films/product/iphone-11-pro-product-tpl-cc-us-2019_1280x720h.mp4"